(cl:defpackage kinect_node-srv
  (:use )
  (:export
   "KINECTSAFEDISTANCE"
   "<KINECTSAFEDISTANCE-REQUEST>"
   "KINECTSAFEDISTANCE-REQUEST"
   "<KINECTSAFEDISTANCE-RESPONSE>"
   "KINECTSAFEDISTANCE-RESPONSE"
   "KINECTDATA"
   "<KINECTDATA-REQUEST>"
   "KINECTDATA-REQUEST"
   "<KINECTDATA-RESPONSE>"
   "KINECTDATA-RESPONSE"
  ))

