(cl:in-package arduino_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LINSPEED-VAL
          LINSPEED
          ANGSPEED-VAL
          ANGSPEED
          LF_ENABLE-VAL
          LF_ENABLE
          LF_DIRECTION-VAL
          LF_DIRECTION
          LF_SERVO_ANGLE-VAL
          LF_SERVO_ANGLE
          LF_SERVO_PWM-VAL
          LF_SERVO_PWM
          LF_WHEEL_RPM-VAL
          LF_WHEEL_RPM
          LF_MOTOR_SIGNAL-VAL
          LF_MOTOR_SIGNAL
          RF_ENABLE-VAL
          RF_ENABLE
          RF_DIRECTION-VAL
          RF_DIRECTION
          RF_SERVO_ANGLE-VAL
          RF_SERVO_ANGLE
          RF_SERVO_PWM-VAL
          RF_SERVO_PWM
          RF_WHEEL_RPM-VAL
          RF_WHEEL_RPM
          RF_MOTOR_SIGNAL-VAL
          RF_MOTOR_SIGNAL
          LR_ENABLE-VAL
          LR_ENABLE
          LR_DIRECTION-VAL
          LR_DIRECTION
          LR_SERVO_ANGLE-VAL
          LR_SERVO_ANGLE
          LR_SERVO_PWM-VAL
          LR_SERVO_PWM
          LR_WHEEL_RPM-VAL
          LR_WHEEL_RPM
          LR_MOTOR_SIGNAL-VAL
          LR_MOTOR_SIGNAL
          RR_ENABLE-VAL
          RR_ENABLE
          RR_DIRECTION-VAL
          RR_DIRECTION
          RR_SERVO_ANGLE-VAL
          RR_SERVO_ANGLE
          RR_SERVO_PWM-VAL
          RR_SERVO_PWM
          RR_WHEEL_RPM-VAL
          RR_WHEEL_RPM
          RR_MOTOR_SIGNAL-VAL
          RR_MOTOR_SIGNAL
))