Header header

std_msgs/Float32 linSpeed
std_msgs/Float32 angSpeed

std_msgs/Bool LF_enable
std_msgs/Bool LF_direction
std_msgs/Int8 LF_servo_angle
std_msgs/Int16 LF_servo_pwm
std_msgs/Float32 LF_wheel_rpm
std_msgs/Int8 LF_motor_signal

std_msgs/Bool RF_enable
std_msgs/Bool RF_direction
std_msgs/Int8 RF_servo_angle
std_msgs/Int16 RF_servo_pwm
std_msgs/Float32 RF_wheel_rpm
std_msgs/Int8 RF_motor_signal

std_msgs/Bool LR_enable
std_msgs/Bool LR_direction
std_msgs/Int8 LR_servo_angle
std_msgs/Int16 LR_servo_pwm
std_msgs/Float32 LR_wheel_rpm
std_msgs/Int8 LR_motor_signal

std_msgs/Bool RR_enable
std_msgs/Bool RR_direction
std_msgs/Int8 RR_servo_angle
std_msgs/Int16 RR_servo_pwm
std_msgs/Float32 RR_wheel_rpm
std_msgs/Int8 RR_motor_signal
