Header header

std_msgs/Float32 linSpeed
std_msgs/Float32 angSpeed

std_msgs/Bool LF_motor_enable
std_msgs/Bool LF_motor_dir
std_msgs/Float32 LF_wheel_rpm
std_msgs/Int16 LF_motor_cmd

std_msgs/Float32 LF_servo_angle
std_msgs/Int16 LF_servo_cmd


std_msgs/Bool RF_motor_enable
std_msgs/Bool RF_motor_dir
std_msgs/Float32 RF_wheel_rpm
std_msgs/Int16 RF_motor_cmd

std_msgs/Float32 RF_servo_angle
std_msgs/Int16 RF_servo_cmd

std_msgs/Bool LR_motor_enable
std_msgs/Bool LR_motor_dir
std_msgs/Float32 LR_wheel_rpm
std_msgs/Int16 LR_motor_cmd

std_msgs/Float32 LR_servo_angle
std_msgs/Int16 LR_servo_cmd

std_msgs/Bool RR_motor_enable
std_msgs/Bool RR_motor_dir
std_msgs/Float32 RR_wheel_rpm
std_msgs/Int16 RR_motor_cmd

std_msgs/Float32 RR_servo_angle
std_msgs/Int16 RR_servo_cmd
